---
volumes:
  mariadb-data: {}

services:
  traefik:
    environment:
      # Public test keys, never use this override in production.
      # https://developers.cloudflare.com/turnstile/troubleshooting/testing/
      TURNSTILE_PUBLIC_KEY: 1x00000000000000000000AA
      TURNSTILE_PRIVATE_KEY: 1x0000000000000000000000000000000AA
  ojs:
    environment:
      INGRESS_SCHEME: http
      OJS_SMTP_SERVER: mailpit
      OJS_SMTP_PORT: "1025"
    depends_on:
      database-init:
        condition: service_completed_successfully
      mariadb:
        condition: service_healthy
  mailpit:
    image: axllent/mailpit:v1.31@sha256:ed9b00c609e77e99c79b93f1178255ebc271868920f2c69a8d166bd5634ed10d
    ports:
      - "1025:1025"
      - "8025:8025"

  database-init:
    image: ghcr.io/lehigh-university-libraries/base:3.2.2.0@sha256:dcda155385ed3811e6192f6b663b978154c9621bb8edc6c863512d9b6de13182
    restart: "no"
    networks:
      default:
    environment:
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_NAME: ${DB_NAME:-ojs}
      DB_USER: ${DB_USER:-ojs}
      DB_CHARACTER_SET: utf8
      DB_COLLATION: utf8_general_ci
    secrets:
      - source: DB_ROOT_PASSWORD
      - source: OJS_DB_PASSWORD
        target: DB_PASSWORD
    entrypoint: /usr/local/bin/init-database.sh
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    restart: unless-stopped
    image: ghcr.io/lehigh-university-libraries/mariadb:11@sha256:9c6a92222f8a877fd7b9e567130381eb2716b970ff0ed460bd03eab746886488
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    secrets:
      - source: DB_ROOT_PASSWORD
