volumes:
  mariadb-data: {}

secrets:
  DB_ROOT_PASSWORD:
    file: ./secrets/DB_ROOT_PASSWORD
services:
  init:
    volumes:
      - ./docker-compose.override.yaml:/docker-compose.override.yaml:ro
  ojs:
    environment:
      OJS_ENABLE_HTTPS: "false"
    volumes:
      - ./rootfs/var/www/ojs/plugins/themes/lrsj:/var/www/ojs/plugins/themes/lrsj:ro
    secrets:
      - source: DB_ROOT_PASSWORD
    depends_on:
      mariadb:
        condition: service_started
  mariadb:
    image: islandora/mariadb:6.0.7@sha256:b523b9cf9ba1cf1e7f7db139921ff8fe9615ba641a0f9ebdd66380a3b5383bd0
    ports:
      - 3366:3306
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    secrets:
      - source: DB_ROOT_PASSWORD
