volumes:
  mariadb-data: {}

secrets:
  DB_ROOT_PASSWORD:
    file: ./secrets/DB_ROOT_PASSWORD
services:
  init:
    volumes:
      - ./docker-compose.override.yaml:/docker-compose.override.yaml:ro
  ojs:
    environment:
      OJS_ENABLE_HTTPS: "false"
      OJS_BASE_URL: http://localhost:8888
    volumes:
      - ./rootfs/var/www/ojs/plugins/themes/lrsj:/var/www/ojs/plugins/themes/lrsj:ro
      - ./rootfs/var/www/ojs/plugins/themes/lehigh:/var/www/ojs/plugins/themes/lehigh:ro
    secrets:
      - source: DB_ROOT_PASSWORD
    depends_on:
      mariadb:
        condition: service_started
  mariadb:
    image: islandora/mariadb:6.4.3@sha256:8f41414cba3286567e0590fa5428e2860e3351f13b1377666b1d362b01e6fe6e
    ports:
      - 3366:3306
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    secrets:
      - source: DB_ROOT_PASSWORD
