name: build-push

on:
  push:

permissions:
  contents: read

jobs:
  build-push:
    uses: lehigh-university-libraries/gha/.github/workflows/build-push-ghcr.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
