name: lint-test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: lint-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0

      - run: make lint
      - run: cp compose.override-example.yaml compose.override.yaml
      - run: make test
      - if: failure()
        run: docker compose logs
